apiVersion: apps/v1
kind: Deployment
metadata:
  name: okteto-hello
spec:
  selector:
    matchLabels:
      app: okteto-hello
  replicas: 1
  template:
    metadata:
      labels:
        app: okteto-hello
    spec:
      containers:
      - name: okteto-hello
        image: okteto.dev/okteto-hello:latest
        ports:
        - containerPort: 8080